CREATE OR REPLACE PACKAGE JPROG AUTHID CURRENT_USER AS
FUNCTION TAXI ("value" IN NUMBER)
 RETURN NUMBER
AS LANGUAGE JAVA
NAME 'jprog.Stored.tax(double) return double';
PROCEDURE HELLO ("val" IN OUT VARCHAR2)
AS LANGUAGE JAVA
NAME 'jprog.Stored.hello(java.lang.String[])';
END JPROG;
/