CREATE ROLE orax;

GRANT
    EXECUTE ANY PROCEDURE,
    CREATE PROCEDURE,
    CREATE USER,
    CREATE JOB,
    QUERY REWRITE,
    CREATE SESSION,
    DEBUG ANY PROCEDURE,
    CREATE VIEW,
    DROP PUBLIC SYNONYM,
    CREATE ANY INDEX,
    DEBUG CONNECT SESSION,
    CREATE ROLE,
    ALTER SESSION,
    MANAGE SCHEDULER,
    CREATE TYPE,
    CREATE PUBLIC SYNONYM,
    CREATE ANY DIRECTORY,
    CREATE SEQUENCE,
    CREATE TRIGGER,
    CREATE SYNONYM,
    CREATE TABLE
TO orax;

GRANT orax TO ora41, ora61, ora62;

